pipeline {
  environment {
    registry = "sureshraju1234/helloworld-python"
    registryCredential = 'dockerhubdockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git branch: 'main', url: 'https://github.com/SURESHRAJU1234/cicd.git'
       
      }
    }
    stage('Building image') {
      steps{
        script {
          //dockerImage = docker.build registry + ":$BUILD_NUMBER"
          sh '''
            cd app
            docker build -t helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER} .
            docker tag helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER} sureshraju1234/helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER}
            docker images
          '''
        }
      }
    }
    stage('Push Image') {
        steps {
            withDockerRegistry([ credentialsId: "dockerhubdockerhub", url: "" ]) {
                sh  'docker push sureshraju1234/helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER}'
              
            }
        }
    }
    stage('k8s deploy') {
    	steps {
	    kubernetesDeploy(	
	      config: 'app/deployment.yaml',
	      kubeconfigId: 'k8s',
	      enableConfigSubstitution: true
	    )
	}
    }
  }
}
