pipeline {
  environment {
    registry = "sureshraju1234/helloworld-python"
    registryCredential = 'dockerhubdockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/SURESHRAJU1234/cicd.git'
       
      }
    }
    stage('Building image') {
      steps{
        script {
          //dockerImage = docker.build registry + ":$BUILD_NUMBER"
          sh '''
            cd app
            docker build -t helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER} .
            docker tag helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER} sureshraju1234/helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER}
            docker images
          '''
        }
      }
    }
    stage('Push Image') {
        steps {
            withDockerRegistry([ credentialsId: "dockerhubdockerhub", url: "" ]) {
                sh  'docker push sureshraju1234/helloworld-python:${GIT_BRANCH}-${BUILD_NUMBER}'
              
            }
        }
    }
    stage('k8s deploy') {
    	steps {
	   withKubeConfig([credentialsId: 'k8stoken', serverUrl: 'https://EB7ACAD5EF478F9332417D4A12201AF2.gr7.us-west-2.eks.amazonaws.com']) {
             sh '''
                echo ${GIT_BRANCH}
		if [ "$GIT_BRANCH" = "main" ]; then
    			echo "main branch. Deploying to K8S cluster"
			cat kubernetes/deployment.yaml | sed "s/{{DOCKER_TAG}}/${GIT_BRANCH}-${BUILD_NUMBER}/g" | kubectl apply -f -
		else
			echo "Not a main branch, skipping kubernetes deployment"
		fi
              ''' 
            }
	}
    }
  }
}
